### PR TITLE
mcookie - fix providing /dev/random or /dev/urandom as file leads to infinite loop

### LINKED ISSUE #264: mcookie: providing `/dev/random` or `/dev/urandom` as file leads to infinite loop
Specifying `/dev/random` or `/dev/urandom` as value for `-f`/`--file` leads to an infinite loop whereas it works fine with the original `mcookie`:
```
$ mcookie -f /dev/random
2e2d8ba3dd944eb3882562000cfb68b6
$ mcookie -f /dev/urandom
1a0ba0dfdc184d2c977a0d0332c19120
```

### PR DESCRIPTION
**Pull request by quangcito**
fixes #264 

Fixes an infinite loop when `mcookie` reads from `/dev/random` or `/dev/urandom` without a `--max-size`.

The issue occurred because `read_to_end()` was used on these non-terminating character devices.

This PR checks if the input file is a character device. If so, and no `--max-size` is given, it reads only a limited number of bytes (1024) instead of attempting to read indefinitely. This aligns behavior with the original `mcookie`.

Tested successfully with `/dev/random` and `/dev/urandom`.

### CODE REVIEW

File: tests/by-util/test_mcookie.rs [hunk 1]
```diff
@@ -63,3 +63,34 @@ fn test_seed_files_and_max_size() {
         file2.path().to_str().unwrap()
     ));
 }
+
+#[test]
+#[cfg(unix)] // Character devices like /dev/zero are a Unix concept
+fn test_char_device_input() {
+    let res_no_limit = new_ucmd!().arg("-f").arg("/dev/zero").succeeds();
+
+    let stdout_no_limit = res_no_limit.no_stderr().stdout_str();
```
Comment (cakebaker) [inline tests/by-util/test_mcookie.rs:72]: A detail: you could call `trim_end()` on this line, which allows you to remove it from lines 73 and 75. The same applies for the `stdout_verbose` var.

Comment (quangcito) [reply tests/by-util/test_mcookie.rs:72]: Feedback received, updating shortly.

**Comment by cakebaker** [comment]
Can you please run `cargo fmt`?

**Comment by quangcito** [comment]
> It looks good, though unfortunately there is a conflict with the changes from your other PR :|

I will resolve the conflict.

**Comment by cakebaker** [comment]
Thanks :)
